wtf:
  colors:
    background: gray
    border:
      focusable: darkslateblue
      focused: orange
      normal: gray
  grid:
    # How _wide_ the columns are, in terminal characters. In this case we have
    # five columns, each of which are 37 characters wide
    columns: [37, 37, 37, 37, 37]

    # How _high_ the rows are, in terminal lines. In this case we have five rows
    # that support ten line of text, and one of four
    rows: [10, 10, 10, 10, 10, 4]
  refreshInterval: 1
  mods:
    bamboohr:
      enabled: true
      position:
        top: 0
        left: 0
        height: 2
        width: 1
      refreshInterval: 900
    clocks:
      colors:
        rows:
          even: "lightblue"
          odd: "white"
      enabled: true
      locations:
        # From https://en.wikipedia.org/wiki/List_of_tz_database_time_zones
        Avignon: "Europe/Paris"
        Barcelona: "Europe/Madrid"
        Dubai: "Asia/Dubai"
        UTC: "Etc/UTC"
        Vancouver: "America/Vancouver"
        Toronto: "America/Toronto"
      position:
        top: 3
        left: 1
        height: 1
        width: 1
      refreshInterval: 15
      # Valid options are: alphabetical, chronological
      sort: "alphabetical"
    cmdrunner:
      args: ["-g", "batt"]
      cmd: "pmset"
      enabled: true
      position:
        top: 6
        left: 2
        height: 1
        width: 2
      refreshInterval: 30
    gcal:
      colors:
        title: "red"
        description: "lightblue"
        highlights:
        - ['1on1|1\/11', 'green']
        - ['apple|google|aws', 'blue']
        - ['interview|meet\ ', 'lightseagreen']
        - ['lunch', 'yellow']
        past: "gray"
      conflictIcon: "ðŸš¨"
      currentIcon: "ðŸ’¥"
      displayResponseStatus: true
      email: "your.email@example.com"
      enabled: true
      eventCount: 12
      position:
        top: 0
        left: 0
        height: 4
        width: 1
      refreshInterval: 300
      secretFile: "~/.config/wtf/gcal/client_secret.json"
      withLocation: true
    gspreadsheets:
      colors:
        values: "green"
      cells:
        names:
        - "Cell 1 name"
        - "Cell 2 name"
        addresses:
        - "A1"
        - "A2"
      enabled: true
      position:
        top: 0
        left: 0
        width: 1
        height: 1
      refreshInterval: "300"
      secretFile: "~/.config/wtf/gspreadsheets/client_secret.json"
      sheetId: "id_of_google_spreadsheet"
    git:
      commitCount: 5
      enabled: true
      position:
        top: 0
        left: 2
        height: 2
        width: 3
      refreshInterval: 8
      repositories:
      - "/Users/chris/go/src/github.com/senorprogrammer/wtf"
    github:
      enabled: true
      position:
        top: 2
        left: 2
        height: 2
        width: 3
      refreshInterval: 300
      repositories:
        repo-name: "owner id"
        wtf: "senorprogrammer"
      username: "senorprogrammer"
    jira:
      colors:
        rows:
          even: "lightblue"
          odd: "white"
      domain: "https://company.atlassian.net"
      enabled: true
      position:
        top: 1
        left: 1
        height: 1
        width: 1
      project: "WTF"
      refreshInterval: 900
      username: "chris.cummer"
    newrelic:
      applicationId: 10594735
      enabled: true
      deployCount: 10
      position:
        top: 4
        left: 2
        height: 2
        width: 3
      refreshInterval: 900
    opsgenie:
      displayEmpty: true
      enabled: true
      position:
        top: 2
        left: 0
        height: 2
        width: 1
      refreshInterval: 21600
    power:
      enabled: true
      position:
        top: 5
        left: 0
        height: 2
        width: 1
      refreshInterval: 15
    security:
      enabled: true
      position:
        top: 4
        left: 0
        height: 2
        width: 1
      refreshInterval: 3600
    status:
      enabled: false
      position:
        top: 5
        left: 0
        height: 1
        width: 1
      refreshInterval: 1
    system:
      enabled: true
      position:
        top: 5
        left: 1
        height: 2
        width: 1
      refreshInterval: 3600
    todo:
      checkedIcon: "X"
      colors:
        checked: gray
        highlight:
          fore: "black"
          back: "orange"
      enabled: true
      filename: "todo.yml"
      position:
        top: 0
        left: 1
        height: 2
        width: 1
      refreshInterval: 3600
    weather:
      # From http://openweathermap.org/help/city_list.txt
      cityids:
      - 3370352
      - 1283240
      colors:
        current: "lightblue"
      enabled: true
      language: "EN"
      position:
        top: 2
        left: 1
        height: 1
        width: 1
      refreshInterval: 90
      tempUnit: "C"
    blockfolio:
      enabled: true
      displayHoldings: true
      refreshInterval: 400
      device_token: "device token here, you can find how to get it here https://github.com/bob6664569/blockfolio-api-client"
      colors:
        name: blue
        grows: green
        drop: red
      position:
        top: 3
        left: 1
        width: 1
        height: 1
