name: static check
on: pull_request

jobs:
  imports:
    name: Imports
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3.5.2
    - name: check
      # uses: grandcolline/golang-github-actions@4356d0458ea4bfdb55fcb296437812acef970f9b
      uses: senorprogrammer/golang-github-actions@c2675d08254b17c070e524b3d907cfaf05fbae6f
      with:
        run: imports
        token: ${{ secrets.GITHUB_TOKEN }}

  errcheck:
    name: Errcheck
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3.5.2
    - name: check
      # uses: grandcolline/golang-github-actions@4356d0458ea4bfdb55fcb296437812acef970f9b
      uses: senorprogrammer/golang-github-actions@c2675d08254b17c070e524b3d907cfaf05fbae6f
      with:
        run: errcheck
        token: ${{ secrets.GITHUB_TOKEN }}

  #lint:
    #name: Lint
    #runs-on: ubuntu-latest
    #steps:
    #- uses: actions/checkout@v3.5.2
    #- name: check
      #uses: grandcolline/golang-github-actions@4356d04
      #with:
        #run: lint
        #token: ${{ secrets.GITHUB_TOKEN }}

  shadow:
    name: Shadow
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3.5.2
    - name: check
      # uses: grandcolline/golang-github-actions@4356d0458ea4bfdb55fcb296437812acef970f9b
      uses: senorprogrammer/golang-github-actions@c2675d08254b17c070e524b3d907cfaf05fbae6f
      with:
        run: shadow
        token: ${{ secrets.GITHUB_TOKEN }}

  staticcheck:
    name: StaticCheck
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3.5.2
    - name: check
      # uses: grandcolline/golang-github-actions@4356d0458ea4bfdb55fcb296437812acef970f9b
      uses: senorprogrammer/golang-github-actions@c2675d08254b17c070e524b3d907cfaf05fbae6f
      with:
        run: staticcheck
        token: ${{ secrets.GITHUB_TOKEN }}

  #sec:
    #name: Sec
    #runs-on: ubuntu-latest
    #steps:
    #- uses: actions/checkout@v3.5.2
    #- name: check
      #uses: grandcolline/golang-github-actions@4356d04
      #with:
        #run: sec
        #token: ${{ secrets.GITHUB_TOKEN }}
        #flags: "-exclude=G104"
